# Location of stored data
data_path: /project/3023001.06/Simulations/kenneth_test/original_data/
seg_path: /project/3023001.06/Simulations/kenneth_test/simulations/segmentation_data/
simnibs_bin_path: /home/affneu/kenvdzee/SimNIBS-4.0/bin/
subject_subfolder: 1
output_location: /project/3023001.06/Simulations/kenneth_test/simulations/posthoc/amygdala/

overwrite_simnibs: 0

# Structure of subfolders containing T1 and T1 images
## It is easier to store the subject data of each participant in an individual subfolder
t1_path_template: sub-%1$03d/*t1mprage*T1w.nii.gz
t2_path_template: sub-%1$03d/*t2space*T2w.nii.gz

transducer: 
  n_elements: 4 # number of elements in the transducer
  Elements_ID_mm: [0, 30.1788, 42.1388, 51.1088]
  Elements_OD_mm: [29.62, 41.58, 50.55, 57.94]
  curv_radius_mm: 62.94 # radius of curvature of the bowl 
  dist_to_plane_mm: 52.38 # distance to the transducer plane from the geometric focus
  source_amp: 199270 # [Pa]
  source_phase_deg: [0, 0.0003, 0.0001, 274.5601] # source phase [deg]
  source_freq_hz: 250e3 # [Hz] the central frequency

expected_focal_distance_mm: 60.9 # expected distance to the stimulation focus
transducer_from_localite: 0 # should we load the transducer locations from the localite file(s) 

using_donders_hpc: 1 # are the simulations run on the HPC cluster?
charm_debug: 0
overwrite_simnibs: 0
use_forceqform: 1

run_posthoc_water_sims: 1
run_heating_sims: 1

thermal:
  duty_cycle: 0.3 # [float between 0 and 1]
  iti: 121 # [s]
  n_trials: 1 # [integer]
  stim_duration: 120 # [s]
  continuous_protocol: 1 # [binary]
  # Pulse repetition frequency is not used since the cooling effects between these cycles are limited

  # These should only be changed if they don't meet the criteria described in "run_heating_simulations"
  sim_time_steps: 0.01 # [s]
  post_stim_time_step_dur: 0.1 # [integer]
  #on_off_step_duration: 0.1 # [s]
  equal_steps: 0 # [binary]