data_path: /home/affneu/kenvdzee/Documents/Ernie_T1_T2/ # the folder with either a) t1 & t2 images, or b) t1 image and the segmentation results, e.g., Ernie subject from SimNIBS
simnibs_bin_path: /home/affneu/kenvdzee/SimNIBS-4.0/bin/ # change to simnibs install
output_location: /project/3023001.06/Simulations/kenneth_test/simulations/exploratory/positioning/

t1_path_template: sub-001_T1.nii.gz # path to T1 relative to data_path; all string substitutions will be done using subject_id
t2_path_template: sub-001_T2.nii.gz # path to T2 relative to data_path; all string substitutions will be done using subject_id

transducer: 
  n_elements: 10 # number of elements in the transducer
  Elements_ID_mm: [10, 22.3, 30, 36.3, 41.7, 46.5, 51, 55.1, 58.9, 62.5]
  Elements_OD_mm: [21.3, 29.1, 35.3, 40.7, 45.6, 50, 54.1, 58, 61.6, 65]
  curv_radius_mm: 75 # radius of curvature of the bowl 
  dist_to_plane_mm: 65.3 # distance to the transducer plane from the geometric focus
  source_amp: 117192 # [Pa]
  source_phase_deg: [0, 360, 56, 83, 103, 126, 145, 139, 256, 142] # source phase [deg]
  pos_t1_grid: [84,182,262] #[84,182,250]
  source_freq_hz: 300e3 # [Hz] the central frequency

focus_pos_t1_grid: [103,172,208]

default_grid_dims: [144, 144, 256]

thermal:
  duty_cycle: 0.5 # share of the stimulation duration during which the stimulation is on
  sim_time_steps: 0.1 # [s] simulation time steps during the stimulation period
  temp_0: 37 #[deg C] initial temperature, currently not used
  stim_duration: 0.6 # [s] stimulation duration within a trial
  iti: 1.2 # interval between the trials, from the start of one trial to the start of another [s]
  n_trials: 12 # number of trials to simulate; the total simulated duration is then n_trials*iti seconds



