# Location of stored data
data_path: /project/3023001.06/Simulations/kenneth_test/original_data/
seg_path: /project/3023001.06/Simulations/kenneth_test/simulations/segmentation_data/
simnibs_bin_path: /home/affneu/kenvdzee/SimNIBS-4.0/bin/
subject_subfolder: 0
output_location: /project/3023001.06/Simulations/kenneth_test/simulations/exploratory/positioning/

overwrite_simnibs: 0

# Structure of subfolders containing T1 and T1 images
## It is easier to store the subject data of each participant in an individual subfolder
t1_path_template: sub-%1$03d/*t1mprage*T1w.nii.gz
t2_path_template: sub-%1$03d/*t2space*T2w.nii.gz

transducer: 
  n_elements: 4 # number of elements in the transducer
  Elements_ID_mm: [0, 30.1788, 42.1388, 51.1088]
  Elements_OD_mm: [29.62, 41.58, 50.55, 57.94]
  curv_radius_mm: 62.94 # radius of curvature of the bowl 
  dist_to_plane_mm: 52.38 # distance to the transducer plane from the geometric focus
  source_amp: 212000 # [Pa] 30=183600, 35=198300, 40=212000
  source_phase_deg: [0, 0, 358.0546, 272.2390] # source phase [deg]
  pos_t1_grid: [210, 184, 117]
  source_freq_hz: 250e3 # [Hz] the central frequency

focus_pos_t1_grid: [134, 167, 129]

expected_focal_distance_mm: 64.5 # expected distance to the stimulation focus
transducer_from_localite: 0 # should we load the transducer locations from the localite file(s) 

using_donders_hpc: 1 # are the simulations run on the HPC cluster?
charm_debug: 0
overwrite_simnibs: 0
use_forceqform: 1

run_source_setup: 1 # Should we set up acoustic source? useful to switch off to look at initial segmentation results only
run_acoustic_sims: 0
run_posthoc_water_sims: 0
run_heating_sims: 0